application/apps/ads/urls.py
from django.conf.urls import patterns, url
from . import views
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^ad/(?P<pk>\d+)/$', views.AdView.as_view(), name='ad_detail'),
    url(r'^create/$', views.AdCreateView.as_view(), name='ad_create'),
    url(r'^update/(?P<pk>\d+)/$', views.AdUpdateView.as_view(),
        name='ad_update'),
    url(r'^delete/(?P<pk>\d+)/$', views.AdDeleteView.as_view(),
        name='ad_delete'),
    url(r'^delete/success/$', TemplateView.as_view(template_name='ads/ad_success_delete.html'),
        name='ad_success_delete'),


    url(r'^ad_api/product_type_fields/(?P<product_type>\d+)/(?P<is_request>\d+)$', views.get_product_type_fields, name='get_product_type_fields'),
    url(r'^ad_api/product_type_fields/(?P<product_type>\d+)/$', views.get_product_type_fields, name='get_product_type_fields'),
    url(r'^ad_api/product_types/(?P<product_category>\d+)/$', views.get_product_types, name='get_product_types'),

    url(r'^ad_api/upload_image/$', views.AdImageCreateView.as_view(), name='upload_image'),
    url(r'^ad_api/upload_file/$', views.AdFileCreateView.as_view(), name='upload_file'),
    url(r'^ad_api/get_provision/$', views.GetBidpartProvisionView.as_view(), name='get_provision'),

    url(r'^show_buy_sell/(?P<show>\w+)/$', views.show_buy_sell, name='show_buy_sell'),

    url(r'^([\w\d\-_]+)/([\w\d\-_]+)/([\w\d\-_]+)/$', views.AdsListView.as_view(), name='ad_filter'),
    url(r'^([\w\d\-_]+)/([\w\d\-_]+)/$', views.AdsListView.as_view(), name='ad_filter'),
    url(r'^([\w\d\-_]+)/$', views.AdsListView.as_view(), name='ad_filter'),
    url(r'^$', views.AdsListView.as_view(), name='ad_filter')
)

application/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

#noinspection PyPackageRequirements
urlpatterns = patterns('',
    # Examples:
    # url(r'^application/', include('application.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),

    url(r'^accounts/', include('application.apps.accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^currencies/', include('currencies.urls')),

    url(r'^notifications/', include('application.libs.notifications.urls', namespace='notifications')),
    url(r'^blog/', include('application.apps.blog.urls', namespace='blog')),
    url(r'^invoice/', include('application.apps.invoice.urls', namespace='invoice')),
    url(r'^page/', include('application.apps.cms.urls', namespace='cms')),
    url(r'^contact/', include('application.apps.contact.urls', namespace='contact')),
    url(r'^faq/', include('application.apps.faq.urls', namespace='faq')),
    url(r'^deals/', include('application.apps.deals.urls', namespace='deals')),

    url(r'^edr/', include('application.apps.edr.urls', namespace='edr')),
    url(r'^interest/', include('application.apps.interest.urls', namespace='interest')),

    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'', include('debug_toolbar_user_panel.urls')),
   )
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^500/$', 'django.views.generic.simple.direct_to_template', {'template': '500.html'}),
        (r'^404/$', 'django.views.generic.simple.direct_to_template', {'template': '404.html'}),

        (r'^template/password_change_done/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_change_done.html'}),
        (r'^template/password_reset_complete/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_complete.html'}),
        (r'^template/password_reset_confirm/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_confirm.html'}),
        (r'^template/password_reset_done/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_done.html'}),
        (r'^template/password_reset_email/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_email.html'}),
    )

urlpatterns += patterns('',
        url(r'^', include('application.apps.ads.urls', namespace='ads')),
   )

application/apps/ads/models.py
import hashlib
from django.contrib.auth.models import User
from django.core.cache import cache
from django.db import models
from django.core.urlresolvers import reverse, resolve
from autoslug import AutoSlugField
from decimal import Decimal
from currencies.models import Currency
from django.db.models import Manager
from django.db.models.query import QuerySet
from django.utils.datastructures import SortedDict
from application.apps.accounts.models import UserProfile, BusinessProfile
from django.utils.translation import ugettext_lazy as _, ugettext
from application.apps.accounts.functions import string_with_title
from application.apps.files.models import Image, File
from application.apps.locale.models import locale_model, DEFAULT_FIELD


def cached_queryset(queryset, timeout, cache_key=None):
    if cache_key is None:
        cache_key = hashlib.md5(str(queryset.query)).hexdigest()
    cache_ = cache.get(cache_key)
    if cache_:
        queryset = cache_
    else:
        cache.set(cache_key, queryset, timeout)
    return queryset


class AdsQuerySet(QuerySet):
    def annotate_deal_state_count(self, state):
        return self.extra(
            select=SortedDict([
                ('num_%s' % state, "SELECT COUNT(*) FROM deals_deal "
                                   "WHERE deals_deal.ad_id = ads_ad.id "
                                   "AND state = %s"),
            ]),
            select_params=(str(state),)
        )


class AdsManager(Manager):

    def get_query_set(self):
        return AdsQuerySet(self.model, using=self._db)

    def annotate_deal_state_count(self, *args, **kwargs):
        return self.get_query_set().annotate_deal_state_count(*args, **kwargs)

    def featured(self, prefetch=True):
        queryset = self.filter(active=True, amount__gt=0)
        queryset = queryset.order_by('-featured', '-num_views', '-created')

        if prefetch:
            queryset = queryset.select_related('product_type')
            queryset = queryset.select_related('currency')
            queryset = queryset.prefetch_related('product_type')
            queryset = queryset.prefetch_related('business_domains')
            queryset = queryset.prefetch_related('images')

        return queryset

ad_localized = locale_model({
    'title': ('CharField', {
        'max_length': 64, 'blank': True, 'verbose_name': _('Title'), 'help_text': _('The title of your ad'), 'db_index': True}),
    'description': ('TextField', {
        'blank': True, 'verbose_name': _('Description'),
        'help_text': _('A detailed description of your ad. Use English language to reach a wider audience.')})
})
class Ad(ad_localized):
    """ Ad """

    objects = AdsManager()

    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name=_('Price / pcs'), help_text=_('Help text for the price'))
    currency = models.ForeignKey(Currency, related_name='+', verbose_name='Currency', help_text=_('Help text for the currency'))
    amount = models.IntegerField(verbose_name=_('Amount'), help_text=_('The amount of items you are selling.'))
    published = models.BooleanField(default=True, verbose_name='Published', help_text=_('Help text for published'), db_index=True)

    product_type = models.ForeignKey('ProductType', related_name='ads', verbose_name=_('Product type'), help_text=_('Help text for product type'))
    business_domains = models.ManyToManyField('BusinessDomain', related_name='ads', verbose_name=_('Business domains'), help_text=_('Help text for business domains'))

    updated = models.DateTimeField(auto_now=True, verbose_name=_('Updated'), help_text=_('When the ad was last edited'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Created'), help_text=_('When the ad was created'))
    last_deal_updated = models.DateTimeField(verbose_name=_('Last Deal updated'), blank=True, null=True, help_text=_('When was the last deal updated'))

    active = models.BooleanField(default=True, verbose_name=_('Active'), help_text=_('Use this instead of deleting the ad'), db_index=True)
    creator = models.ForeignKey(UserProfile, verbose_name=_('Creator'), help_text=_('The person who created the ad'))
    owner = models.ForeignKey(BusinessProfile, verbose_name=_('Owner'), help_text=_('The business who owns the ad'))

    youtube_code = models.CharField(max_length=16, blank=True, null=True, verbose_name=_('Youtube url'), help_text=_('An url to a youtube-clip'))

    is_request = models.BooleanField(default=False, verbose_name=_('Buying'), help_text=_('If the ad is wanted'), db_index=True)

    featured = models.BooleanField(default=False, verbose_name=_('Featured'), help_text=_('Featured on the frontpage'), db_index=True)
    num_views = models.IntegerField(default=0, verbose_name=_('Number of views'), help_text=_('Total number of views this ad has'))

    notes = models.TextField(blank=True, verbose_name=_('Your own notes'), help_text=_('Your own notes is not visible to anyone else.'))

    def get_absolute_url(self):
        return reverse('ads:ad_detail', kwargs={'pk': self.pk})

    @property
    def float_price(self):
        return str(float(self.price))

    @property
    def total_price(self):
        return self.price * self.amount

    def user_has_perm(self, user_obj, perm):
        """
        :type user_obj: User
        """
        if perm == 'change_ad':
            if user_obj.is_anonymous():
                return False
            elif user_obj.get_business_profile().pk == self.owner.pk:
                return True
            else:
                return False

    def __unicode__(self):
        return self.get_localized('title', 'en')

    class Meta:
        app_label = string_with_title('ads', _('Ads'))
        verbose_name = _('Ad')
        verbose_name_plural = _('Ads')


class Value(models.Model):
    """ The values for ProductType Fields for the Ad """

    ad = models.ForeignKey('Ad', related_name='value_set')
    field = models.ForeignKey('Field', related_name='value_set')
    value = models.CharField(max_length=256)
    choice_value = models.ForeignKey('FieldChoice', blank=True, null=True)
    min_value = models.CharField(max_length=128, blank=True, default="", help_text=_('Used for requests.'))
    max_value = models.CharField(max_length=128, blank=True, default="", help_text=_('Used for requests.'))

    def get_value(self):
        if self.field.type == 'ChoiceField':
            return self.choice_value
        else:
            return self.field.recast_value(self.value)

    def get_localized(self, field, language_code):
        if field == 'value':
            if self.field.type == 'ChoiceField' and self.choice_value:
                return self.choice_value.get_localized('name', language_code)
            elif self.field.type == 'BooleanField':
                value = self.get_value()
                if value:
                    return _('Yes')
                else:
                    return _('No')
            else:
                return self.get_value()
        else:
            return ''

    def __unicode__(self):
        return unicode(self.value or '')

    class Meta:
        app_label = string_with_title('ads', _('Ads'))
        verbose_name = _('Ad product field value')
        verbose_name_plural = _('Ad product field values')


class BusinessDomain(locale_model('title')):
    """ The business domains that the Ad fits into """

    title = models.CharField(max_length=64)
    slug = AutoSlugField(always_update=True, populate_from='title', unique=True)
    is_unique = models.BooleanField(default=False, verbose_name=_('Is Unique'), help_text=_('If this business domain is selected no other business domain can be selected.'))
    def __unicode__(self):
        return self.title

    class Meta:
        app_label = string_with_title('ads', _('Ads'))
        verbose_name = _('Business domain')
        verbose_name_plural = _('Business domains')
        ordering = ['title']


class ProductType(locale_model('title')):
    """ The product type that the Ad lies in """

    title = models.CharField(max_length=64)
    fields = models.ManyToManyField('Field', related_name='product_types',
        blank=True)
    product_categories = models.ManyToManyField('ProductCategory',
        related_name='product_types')
    slug = AutoSlugField(always_update=True, populate_from='title', unique=True)

    class Meta:
        app_label = string_with_title('ads', _('Ads'))
        verbose_name = _('Product type')
        verbose_name_plural = _('Product types')
        ordering = ['title']

    def __unicode__(self):
        return self.title


class ProductCategory(locale_model('title')):
    """ The categories that the ProductType lies in """

    title = models.CharField(max_length=64)
    slug = AutoSlugField(always_update=True, populate_from='title', unique=True)

    def __unicode__(self):
        return self.title

    class Meta:
        app_label = string_with_title('ads', _('Ads'))
        verbose_name = _('Product category')
        verbose_name_plural = _('Product categories')
        ordering = ['title']


class Field(locale_model(['label', 'help_text'])):
    """ The fields for the ProductType """

    TYPE_CHOICES = (
        ('IntegerField', 'Natural number'),
        ('CharField', 'Textfield'),
        ('TextField', 'Textarea'),
        ('BooleanField', 'Checkbox'),
        ('DecimalField', 'Decimalfield'),
        ('ChoiceField', 'Choices'),
    )

    name = models.CharField(max_length=64)
    required = models.BooleanField()
    type = models.CharField(max_length=64, choices=TYPE_CHOICES)
    suffix = models.CharField(max_length=4, blank=True)
    is_filterable = models.BooleanField(default=False)

    def recast_value(self, value):
        try:
            if self.type == 'IntegerField':
                return int(value)
            elif self.type == 'BooleanField':
                if value == 'False':
                    return False
                else:

application/apps/ads/templates/ads/ad_deals.html
{% load i18n ads_extras %}
<div class="status-info">
	{% if group == 'ads' %}
        <span class="badge{% if ad.num_interested %} badge-info{% endif %}">{{ ad.num_interested }}</span> {% trans 'interests' %} |
        <span class="badge{% if ad.num_active %} badge-info{% endif %}">{{ ad.num_active }}</span> {% trans 'deals' %} |
        <span class="badge{% if ad.num_completed %} badge-info{% endif %}">{{ ad.num_completed }}</span> {% trans 'completed' %}
    {% else %}
        {% for deal in ad.deals.all %}
            {% trans 'State' %}: <span class="badge badge-info">{{ deal.get_state_display }}</span><br />
            {% trans 'Your bid' %}: <span class="badge badge-info">{% price deal.bid deal.currency '' False %}</span>
        {% endfor %}
	{% endif %}

</div>

application/apps/ads/templates/ads/ad_form.html
{% extends "base.html" %}
{% load i18n ads_extras files_extras angular_extras locale_extras %}

{% block content %}
    <form action="{{ request.get_full_path }}" method="post" class="ad-form" enctype="multipart/form-data" ng-init="{{ form|ng_init }}" ng-controller="AdFormController">
        {% csrf_token %}
        {% if form.errors.items %}
            <div class="alert alert-error">
                {% trans 'There are errors, please review the form and submit again.' %}
            </div>
        {% endif %}
        <fieldset>
            <legend>
                {% trans 'Ad type' %}
            </legend>
            <div class="row">
                <div class="span3">
                    <div class="btn-group is_request" buttons-radio data-toggle="buttons-radio" ng-model="fields.is_request.value">
                        <button type="button" class="btn" value="">{% trans 'Selling' %}</button>
                        <button type="button" class="btn" value="true">{% trans 'Buying' %}</button>
                    </div>
                    <input type="hidden" name="is_request" value="{! fields.is_request.value !}">
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>
                {% trans 'Product type' %}
                <small class="pull-right"><em><strong>*</strong> {% trans 'required' %}</em></small>
            </legend>
            <div class="row">
                <div class="span3 {{ form.business_domains.css_classes }}">
                    {{ form.business_domains.label_tag }}
                    {{ form.business_domains }}
                    {{ form.business_domains.errors }}
                </div>
                <div class="span3 {{ form.product_category.css_classes }}">
                    {{ form.product_category.label_tag }}
                    {{ form.product_category }}
                    {{ form.product_category.errors }}
                </div>
                <div class="span3 {{ form.product_type.css_classes }}">
                    {{ form.product_type.label_tag }}
                    <select id="id_product_type" ng-model="fields.product_type.value" ui-select2="" name="product_type" ng-disabled="fields.product_type.loading" class="ng-pristine ng-valid" style="display: none;">
                        <option ng-repeat="choice in fields.product_type.choices" value="{! choice.key !}">{! choice.value !}</option>
                    </select>
                    {{ form.product_type.errors }}
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>{% trans 'Product information' %}</legend>
            <div class="row">
                <div class="span9">
                    <ul class="span9 nav nav-tabs" id="product-info-lang">
                        {% for lang in LANGUAGES %}
                            <li><a href="#product_info-{{ lang.0 }}" data-toggle="tab">{{ lang.1 }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="tab-content {{ form.product_info.css_classes }}" id="id_product_info">
                {% for lang in LANGUAGES %}
                    <div class="row tab-pane" id="product_info-{{ lang.0 }}">
                        {% get_localized_formfield form 'title' lang.0 as title_field %}
                        {% get_localized_formfield form 'description' lang.0 as descr_field %}
                        <div class="span9">
                            <div class="row">
                                <div class="span6 {{ title_field.css_classes }}">
                                    <label for="{{ title_field.auto_id }}">{{ title_field.label }} ({{ lang.1 }})</label>
                                    {{ title_field }}
                                    {{ title_field.errors }}
                                </div>
                                <div class="span3">
                                    <span class="help-inline">{{ title_field.help_text }}</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="span6 {{ descr_field.css_classes }}">
                                    <label for="{{ descr_field.auto_id }}">{{ descr_field.label }} ({{ lang.1 }})</label>
                                    {{ descr_field }}
                                    {{ descr_field.errors }}
                                </div>
                                <div class="span3">
                                    <span class="help-inline">{{ descr_field.help_text }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {{ form.product_info.errors }}
                <script>
                    $(function () {
                        $('#product-info-lang a:first').tab('show');
                    })
                </script>
            </div>


            <div class="row">
                <div class="span3">
                    <div class="{{ form.price.css_classes }}">
                        <label for="id_price">
                            <span ng-hide="fields.is_request.value">{% trans 'Price / pcs' %}</span>
                            <span ng-show="fields.is_request.value">{% trans 'Max price / pcs' %}</span>
                        </label>
                        <div class="input-append price">
                            {{ form.price }}{{ form.currency }}
                        </div>
                        {{ form.price.errors }}
                        <div>
                            <small>{% trans 'Bidparts commission is 10&#37; (minimum € 60) and based on the final price of each individual deal.' %}</small>
                            <hr>
                        </div>
                    </div>
                    <label class="checkbox">
                        <input type="checkbox" name="quote_wanted" ng-model="quote_wanted" ng-change="fields.price.value = 0" />
                        {% trans "Advertise without price" %}
                    </label>

                </div>
                <div class="span3 {{ form.amount.css_classes }}">
                    {{ form.amount.label_tag }}
                    <div class="input-append amount">
                        {{ form.amount }}
                        <div class="add-on">
                            {% trans 'Pcs' %}
                        </div>
                    </div>
                    {{ form.amount.errors }}
                </div>
                <div class="span3">
                    <span class="help-inline">{{ form.amount.help_text }}</span>
                </div>
            </div>
        </fieldset>

        {% if form.product_type.value %}
            <fieldset ng-hide="product_type_fields_url">
                {% include 'ads/ad_form_product_type_fields.html' with form=form %}
            </fieldset>
        {% endif %}
        <fieldset ng-include="product_type_fields_url">
        </fieldset>

        <fieldset>
            <legend>{% trans 'Images' %}</legend>
            <div class="row">
                <div class="span6 images">
                    <div class="well well-small clearfix">
                        <span class="image" ng-repeat="(key, img) in uploaded_images">
                            <img ng-src="{! img !}" />
                            <a class="remove-icon" ng-click="remove_file($event, 'images')" data-key="{! key !}" data-icon="&#xe009;" href="javascript:void(0);"></a>
                        </span>
                        <div style="display:none;">
                            <input type="hidden" value="{! val !}" name="images" ng-repeat="val in fields.images.value" />
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div>
                        <label for="image_upload">{% trans 'Upload image' %}</label>
                        <input id="image_upload" name="image_filename" uploader="{% url ads:upload_image %}" ng-model="image_to_upload" type="file" />
                        <ul class="errorlist">
                            <li ng-repeat="error in fields.images.errors.__all__">{! error !}</li>
                            <li ng-repeat="error in fields.images.errors.image_filename">{! error !}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>{% trans 'Files & documentation' %}</legend>
            <div class="row">
                <div class="span6 files">
                    <div class="well well-small clearfix">
                        <span class="file" ng-repeat="(key, file) in uploaded_files">
                            <a class="file-link" href="{! file !}" target="_blank" data-icon="&#xe00a;"></a>
                            <a class="remove-icon" ng-click="remove_file($event, 'files')" data-key="{! key !}" data-icon="&#xe009;" href="javascript:void(0);"></a>
                        </span>
                    </div>
                    <div style="display:none;">
                        <input type="hidden" value="{! val !}" name="files" ng-repeat="val in fields.files.value" />
                    </div>
                </div>
                <div class="span3">
                    <div>
                        <label for="file_upload">{% trans 'Upload file' %}</label>
                        <input id="file_upload" name="filename" uploader="{% url ads:upload_file %}" ng-model="file_to_upload" type="file" />
                        <ul class="errorlist">
                            <li ng-repeat="error in fields.files.errors.__all__">{! error !}</li>
                            <li ng-repeat="error in fields.files.errors.image_filename">{! error !}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>{% trans 'Youtube' %}</legend>
            <div class="row">
                <div class="span6 {{ form.youtube_code.css_classes }}">
                    {{ form.youtube_code.label_tag }}
                    {{ form.youtube_code }}
                    {{ form.youtube_code.errors }}
                </div>
                <div class="span3">
                    <span class="help-inline">{{ form.youtube_code.help_text }}</span>
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>{% trans 'Your own notes' %}</legend>
            <div class="row">
                <div class="span6 {{ form.notes.css_classes }}">
                    {{ form.notes.label_tag }}
                    {{ form.notes }}
                    {{ form.notes.errors }}
                </div>
                <div class="span3">
                    <span class="help-inline">{{ form.notes.help_text }}</span>
                </div>
            </div>
        </fieldset>

        <div class="form-actions">
            <a class="btn btn-danger pull-left" href="#ad-delete-modal" data-toggle="modal">{% trans 'Delete' %}</a>
            <input class="btn btn-primary pull-right" type="submit" value="{% trans 'Save Ad' %}">
        </div>
    </form>

    {% if ad.pk %}
        <form class="modal hide fade" id="ad-delete-modal" method="post" action="{% url ads:ad_delete ad.pk %}">
            {% csrf_token %}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>{% trans "Delete" %} {{ deal.ad }}</h3>
            </div>
            <div class="modal-body">
                <div class="alert alert-error">
                    {% trans 'Are you sure you want to delete this ad?' %}
                </div>
            </div>
            <div class="modal-footer">
                <input class="btn pull-left" type="submit" data-dismiss="modal" value="{% trans 'Cancel' %}"/>
                <input class="btn btn-danger pull-right" type="submit" value="{% trans 'Delete' %}"/>
            </div>
        </form>
    {% endif %}

{% endblock %}

application/apps/ads/templates/ads/ad_form_product_type_fields.html
{% load i18n %}
<legend>{% trans 'Product specification' %}</legend>
{% for field, db_field in form.product_type_fields %}
    {% if forloop.counter0|divisibleby:"3" %}
        <div class="row">
        <!-- New row every third -->
    {% endif %}
    <div class="span3 {{ field.css_classes }}">
        {{ field.label_tag }}
        {% if db_field.suffix %}
            <div class="input-append spec-suffix">
                {{ field }}
                <div class="add-on">
                    {{ db_field.suffix }}
                </div>
            </div>
        {% else %}
            {{ field }}
        {% endif %}
        {{ field.errors }}
    </div>
    {% if forloop.last or forloop.counter|divisibleby:"3" %}
        <!-- End new row -->
        </div>
    {% endif %}
{% empty %}
    <div class="row">
    	<div class="span12">
    		<p>{% trans 'Please choose a product type' %}</p>
    	</div>
    </div>
{% endfor %}

application/apps/ads/templates/ads/ad_header_search.html
{% load i18n %}
{% load angular_extras %}
<form ng-cloak ng-controller="HeaderFilterController" ng-submit="submit()" ng-init='{{ form|ng_init }}' class="navbar-form pull-left">
    <span class="navbar-form-text">{% trans 'Search for' %}</span>
    {% with search=form.search %}
        <input type="search" class="main-search btn-important" ng-model="fields.{{search.html_name}}.value" placeholder="{{search.label}}">
    {% endwith %}
    <span class="navbar-form-text navbar-form-text-in">{% trans 'in' %}</span>
	{{ form.business_domain }}
    <input type="submit" class="btn btn-important btn-primary" value="{% trans 'Search' %}">

	<div ng-show="filter_open" ng-cloak class="header-filter well">
        <h2>More options!</h2>
	</div>
</form>

application/apps/ads/templates/ads/ad_list_sidebar.html
{% load i18n %}
<div class="page-header filter-header">
    <h3>{% trans 'Filter ads' %}</h3>
</div>
{{ form.business_domain }}
<div id="ad-list-sidebar" class="row sidebar-list well">
	<ul data-field="{{ field }}">
		{% if field == 'product_type' %}
			<li class="back-item">
				<a href="{{back_url}}" class="btn btn-block back">{% trans 'Back' %}</a>
			</li>
		{% endif %}

		{% if all_url %}
			<li class="list-item {% if not active_value %}active{% endif %}">
				<a href="{{all_url}}" class="all-link">
					{{all_string}}
				</a>
			</li>
		{% endif %}
		{% for choice in choices %}
			<li class="list-item {% if choice.value == active_value %}active{% endif %}">
				<a href="{{choice.url}}">
					{{ choice.label }}
                    <span data-icon="&#xe002;"></span>
				</a>
			</li>
		{% endfor %}
	</ul>
</div>

application/apps/ads/templates/ads/ad_success_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="alert alert-success">
        {% trans 'Your ad has been successfully deleted.' %}
    </div>
    <a class="btn" href="/">{% trans 'Continue' %}</a>
{% endblock %}