application/apps/contact/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

application/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

#noinspection PyPackageRequirements
urlpatterns = patterns('',
    # Examples:
    # url(r'^application/', include('application.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),

    url(r'^accounts/', include('application.apps.accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^currencies/', include('currencies.urls')),

    url(r'^notifications/', include('application.libs.notifications.urls', namespace='notifications')),
    url(r'^blog/', include('application.apps.blog.urls', namespace='blog')),
    url(r'^invoice/', include('application.apps.invoice.urls', namespace='invoice')),
    url(r'^page/', include('application.apps.cms.urls', namespace='cms')),
    url(r'^contact/', include('application.apps.contact.urls', namespace='contact')),
    url(r'^faq/', include('application.apps.faq.urls', namespace='faq')),
    url(r'^deals/', include('application.apps.deals.urls', namespace='deals')),

    url(r'^edr/', include('application.apps.edr.urls', namespace='edr')),
    url(r'^interest/', include('application.apps.interest.urls', namespace='interest')),

    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'', include('debug_toolbar_user_panel.urls')),
   )
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^500/$', 'django.views.generic.simple.direct_to_template', {'template': '500.html'}),
        (r'^404/$', 'django.views.generic.simple.direct_to_template', {'template': '404.html'}),

        (r'^template/password_change_done/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_change_done.html'}),
        (r'^template/password_reset_complete/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_complete.html'}),
        (r'^template/password_reset_confirm/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_confirm.html'}),
        (r'^template/password_reset_done/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_done.html'}),
        (r'^template/password_reset_email/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_email.html'}),
    )

urlpatterns += patterns('',
        url(r'^', include('application.apps.ads.urls', namespace='ads')),
   )

application/apps/contact/models.py
from django.db import models


class Ticket(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    cc_myself = models.BooleanField()
    ip = models.IPAddressField()

application/apps/contact/forms.py
from django import forms
from models import Ticket


class ContactForm(forms.ModelForm):
    class Meta:
        model = Ticket
        exclude = ('ip', )

    def __init__(self, request=None, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.request = request

    def save(self, commit=True):
        m = super(forms.ModelForm, self).save(commit=False)

        m.ip = self.request.META['REMOTE_ADDR']

        if commit:
            m.save()
        return m

application/apps/contact/views.py
from django.shortcuts import render, render_to_response
from django.template.loader import get_template
from application import settings
from forms import *
from django.template import RequestContext, Context
from django.core.mail import send_mail


def index(request):
    if request.method == "POST":
        form = ContactForm(data=request.POST, request=request)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['lennart.sjoblom@bidpart.se']

            if cc_myself:
                recipients.append(email)

            email_message = get_template('contact/contact_email.txt').render(Context({
                'email': email,
                'subject': subject,
                'message': message
            }))

            send_mail(subject, email_message, settings.DEFAULT_FROM_EMAIL, recipients)

            form.save()

            return render_to_response('contact/contact_thanks.html', None, context_instance=RequestContext(request))
    else:
        form = ContactForm()

    return render(request, 'contact/contact_form.html', {
        'form': form,
    })

application/apps/contact/templates/contact/contact_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<section>
    <div class="page-header">
        <h1>{% trans "Contact us" %}</h1>
    </div>

    <div class="row">
        <div class="span5">

            <form action="{% url contact:index %}" method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                <fieldset>
                    <div class="control-group {{ form.subject.errors|yesno:"error," }}">
                        <label for="id_subject">{% trans "Subject:" %}</label>
                        <input type="text" class="span5" maxlength="30" name="subject" id="id_subject" value="{{ form.subject.value|default_if_none:"" }}" {% if form.subject.errors %}rel="tooltip" title="{{ form.subject.errors|join:", " }}" {% endif %} />
                    </div>
                    <div class="control-group {{ form.message.errors|yesno:"error," }}">
                        <label for="id_message">{% trans "Message:" %}</label>
                        <textarea name="message" class="span5" id="id_message" rows="7" {% if form.message.errors %}rel="tooltip" title="{{ form.message.errors|join:", " }}" {% endif %}>{{ form.message.value|default_if_none:"" }}</textarea>
                    </div>
                    <div class="control-group {{ form.name.errors|yesno:"error," }}">
                        <label for="id_name">{% trans "Your name:" %}</label>
                        <input type="text" class="span5" maxlength="30" name="name" id="id_name" value="{{ form.name.value|default_if_none:"" }}" {% if form.name.errors %}rel="tooltip" title="{{ form.name.errors|join:", " }}" {% endif %} />
                    </div>
                    <div class="control-group {{ form.email.errors|yesno:"error," }}">
                        <label for="id_email">{% trans "Your e-mail address:" %}</label>
                        <input type="text" class="span5" maxlength="30" name="email" id="id_email" value="{{ form.email.value|default_if_none:"" }}" {% if form.email.errors %}rel="tooltip" title="{{ form.email.errors|join:", " }}" {% endif %} />
                    </div>
                    <div class="control-group {{ form.cc_myself.errors|yesno:"error," }}">
                        <label for="id_cc_myself">{{ form.cc_myself }} {% trans "Send me a copy of the support ticket." %}</label>
                    </div>
                </fieldset>

                <div class="control-group"><input type="submit" value="{% trans 'Send' %}" class="btn" /></div>
            </form>

        </div>
    	<div class="span4">
			<address class="contact well">
                <b>Bidpart AB</b><br />
                <span>Nyborgsgatan 17b</span><br />
                <span>891 34 Örnsköldsvik</span><br />
                <span>Sweden</span><br />
				<br />
				<a href="mailto:info@bidpart.se">info@bidpart.se</a><br />
				<b>{% trans 'Tel' %}:</b> <a href="tel:004666051177">+46 660 511 77</a><br />
                <b>{% trans 'Fax' %}:</b> <a href="fax:004666051120">+46 660 511 20</a>
			</address>
    	</div>
    </div>

</section>

{% endblock %}

application/apps/contact/templates/contact/contact_thanks.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<section>
    <div class="page-header">
        <h1>{% trans "Contact us" %}</h1>
    </div>

    <div class="row">
        <div class="span12">
            <p>{% trans "Thanks for contacting us. We will get back to you shortly." %}</p>
        </div>
    </div>
</section>

{% endblock %}