application/apps/deals/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^create', views.DealsCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.DealsUpdateView.as_view(), name='update'),
)

application/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

#noinspection PyPackageRequirements
urlpatterns = patterns('',
    # Examples:
    # url(r'^application/', include('application.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),

    url(r'^accounts/', include('application.apps.accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^currencies/', include('currencies.urls')),

    url(r'^notifications/', include('application.libs.notifications.urls', namespace='notifications')),
    url(r'^blog/', include('application.apps.blog.urls', namespace='blog')),
    url(r'^invoice/', include('application.apps.invoice.urls', namespace='invoice')),
    url(r'^page/', include('application.apps.cms.urls', namespace='cms')),
    url(r'^contact/', include('application.apps.contact.urls', namespace='contact')),
    url(r'^faq/', include('application.apps.faq.urls', namespace='faq')),
    url(r'^deals/', include('application.apps.deals.urls', namespace='deals')),

    url(r'^edr/', include('application.apps.edr.urls', namespace='edr')),
    url(r'^interest/', include('application.apps.interest.urls', namespace='interest')),

    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'', include('debug_toolbar_user_panel.urls')),
   )
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^500/$', 'django.views.generic.simple.direct_to_template', {'template': '500.html'}),
        (r'^404/$', 'django.views.generic.simple.direct_to_template', {'template': '404.html'}),

        (r'^template/password_change_done/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_change_done.html'}),
        (r'^template/password_reset_complete/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_complete.html'}),
        (r'^template/password_reset_confirm/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_confirm.html'}),
        (r'^template/password_reset_done/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_done.html'}),
        (r'^template/password_reset_email/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_email.html'}),
    )

urlpatterns += patterns('',
        url(r'^', include('application.apps.ads.urls', namespace='ads')),
   )

application/apps/deals/models.py
# coding=utf-8
from decimal import Decimal
import threading
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.db import models
from django.template import Context, Template
from django.utils import timezone, importlib
from application.apps.accounts.models import UserProfile, BusinessProfile
from application.apps.ads.models import Ad
from currencies.models import Currency
from django.utils.translation import ugettext_lazy as _
from application.apps.ads.templatetags.ads_extras import convert_price
from application.apps.cms.models import EmailTemplate


class DealManager(models.Manager):
    pass


class Deal(models.Model):
    """ A deal for an Ad """

    class Meta:
        unique_together = ('ad', 'owner')

    STATES = (
        ('interested', _('Interested')),
        ('active', _('Active')),
        ('completed', _('Completed')),
        ('canceled', _('Canceled')),
    )

    creator = models.ForeignKey(UserProfile)
    owner = models.ForeignKey(BusinessProfile)
    ad = models.ForeignKey(Ad, related_name='deals', verbose_name=_('Ad'))
    state = models.CharField(max_length=32, choices=STATES, default='interested', verbose_name=_('State'))
    bid = models.DecimalField(max_digits=20, decimal_places=2, help_text=_('Optional bid'), verbose_name=_('Bid'))
    price = models.DecimalField(max_digits=20, decimal_places=2, help_text=_('End price'), blank=True, null=True, verbose_name=_('Price'))
    amount = models.IntegerField(verbose_name=_('Amount'), help_text=_('The number of items'))
    price_eur = models.DecimalField(max_digits=20, decimal_places=2, help_text=_('End price (Converted to EUR)'), blank=True, null=True, verbose_name=_('Price converted to EUR'))
    commission = models.DecimalField(max_digits=20, decimal_places=2, help_text=_('Commission'), blank=True, null=True, verbose_name=_('Commission'))
    agent_commission = models.DecimalField(max_digits=20, decimal_places=2, help_text=_('Agent Commission'), blank=True, null=True, verbose_name=_('Agent comission'))
    last_reminder = models.DateTimeField(verbose_name=_('Last reminder'), auto_now_add=True)
    manual_processing = models.BooleanField(verbose_name=_('Manual processing'))
    payed_to_agent = models.BooleanField(verbose_name=_('Payed to agent'))
    cancel_reason = models.TextField(blank=True, null=True, verbose_name=_('Cancel reason'))
    invoice = models.ForeignKey('invoice.Invoice', verbose_name=_('The invoice this deal has auto-created'), blank=True, null=True, help_text=_('If this deal auto-created a invoice, it will be referenced here'))
    renewed = models.DateTimeField(auto_now_add=True, verbose_name=_('Renewed'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Updated'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Created'))

    # actions
    ACTIVATE = 'activate'
    EXTEND = 'extend'
    CANCEL = 'cancel'
    COMPLETE = 'complete'

    @property
    def currency(self):
        return self.ad.currency

    @property
    def float_unit_bid(self):
        if self.bid > 0 and self.amount > 0:
            return str(Decimal(float(self.bid / self.amount)).quantize(Decimal('.00')))
        else:
            return str(Decimal(self.ad.price).quantize(Decimal('.00')))

    def user_has_perm(self, user_obj, perm):
        """
        :type user_obj: User
        """
        if perm == 'change_deal':
            if user_obj.is_anonymous():
                return False
            elif user_obj.get_business_profile().pk == self.ad.owner.pk:
                if self.state == 'completed' or self.state == 'canceled':
                    return False
                else:
                    return True
            else:
                return False

    def do_action(self, action, cancel_reason=None, amount=None, end_price=None):
        if action == self.ACTIVATE:
            self.state = 'active'
            self.renewed = timezone.now()
            self.save()
            threading.Thread(target=self.send_mail,
                             args=('status_changed', self.ad.creator.user.email, self.ad.creator.lang_code)).start()

        elif action == self.EXTEND:
            self.renewed = timezone.now()
            self.save()

        elif action == self.CANCEL:
            self.state = 'canceled'
            if cancel_reason:
                self.cancel_reason = cancel_reason
            else:
                self.cancel_reason = 'No reason supplied.'

            self.save()
            threading.Thread(target=self.send_mail,
                             args=('status_changed', self.ad.creator.user.email, self.ad.creator.lang_code)).start()

        elif action == self.COMPLETE:
            if amount:
                self.amount = amount

            if (self.ad.amount - self.amount) >= 0:
                self.state = 'completed'
                self.ad.amount -= self.amount

                if self.ad.amount == 0:
                    self.ad.published = False
                    other_deals = self.ad.deals.exclude(pk=self.pk)
                    for other_deal in other_deals:
                        other_deal.do_action(self.CANCEL, cancel_reason='Auto cancel, all items are sold.')

                self.ad.save()

                if end_price:
                    self.price = end_price
                else:
                    self.price = self.bid

                self.price_eur = convert_price(self.price, self.currency, Currency.objects.get(code='EUR'))

                commission = importlib.import_module('application.apps.deals.func').commission
                self.commission = commission(self.ad.owner, self.price, self.currency)

                if self.ad.owner.agent_id:
                    agent_commission = importlib.import_module('application.apps.deals.func').agent_commission
                    self.agent_commission = agent_commission(
                        agent=self.ad.owner.agent,
                        bidpart_commission=self.commission,
                        currency=self.currency
                    )

                if (self.price / self.amount) < (self.ad.price * settings.DEAL_MANUAL_PROCESSING_LIMIT):
                    self.manual_processing = True

                _Invoice = importlib.import_module('application.apps.invoice.models').Invoice
                self.invoice = _Invoice.create_from_deals([self], self.ad.owner)

                self.save()

                seller_profile = self.creator if self.ad.is_request else self.ad.creator
                customer_profile = self.ad.creator if self.ad.is_request else self.creator

                if not self.manual_processing:
                    threading.Thread(target=self.send_mail,
                                     args=('invoice', seller_profile.user.email, seller_profile.lang_code)).start()
                    threading.Thread(target=self.send_mail,
                                     args=('completed_customer',customer_profile.user.email, customer_profile.lang_code)).start()

            else:
                raise ValueError('Invalid amount %s of %s' % (amount, self.ad.amount))

        else:
            raise ValueError('Invalid action %s' % action)

        return self

    def created_weeks_ago(self):
        delta = timezone.now() - self.created
        #noinspection PyTypeChecker
        return int(round(delta.days / 7.0, 0))

    def send_mail(self, name, to, lang_code='en'):
        if not isinstance(to, (list, tuple)):
            to = [to]

        template = EmailTemplate.objects.get(name=name)
        context = Context({
            'deal': self,
            'ad_title': self.ad.get_localized('title', lang_code),
            'ad_url': 'http://{0}{1}?next={2}%23deal-{3}'.format(
                settings.BASE_URL,
                reverse('accounts:login'),
                reverse('ads:ad_detail', kwargs={
                    'pk': self.ad.pk
                }),
                self.pk
            )
        })

        lang_code = self.ad.creator.lang_code or 'en'

        subject = template.get_localized('subject', lang_code)
        email_html = Template(template.get_localized('html', lang_code)).render(context)
        email_txt = Template(template.get_localized('txt', lang_code)).render(context)

        message = EmailMultiAlternatives(subject=subject, to=to)
        message.attach_alternative(email_txt, 'text/plain')
        message.attach_alternative(email_html, 'text/html')

        if name == 'invoice':
            if not self.invoice.is_written_to_disk:
                self.invoice.sent_timestamp = timezone.now()
                self.invoice.sent = True
                self.invoice.write_pdf()

            message.attach_file(self.invoice.pdf_path)

        message.send()

    def save(self, *args, **kwargs):
        self.ad.last_deal_updated = timezone.now()
        self.ad.save()
        super(Deal, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s: %s' % (self.ad, self.state)

application/apps/deals/views.py
from django.core.exceptions import PermissionDenied
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
import models
from django.http import HttpResponse, HttpResponseBadRequest
import forms
import json
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from application.apps.accounts.functions import has_active_business_profile


class DealsCreateView(CreateView):
    model = models.Deal
    form_class = forms.CreateDealForm

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: has_active_business_profile(u)))
    def dispatch(self, *args, **kwargs):
        return super(DealsCreateView, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instanciating the form.
        """
        kwargs = super(DealsCreateView, self).get_form_kwargs()
        kwargs.update({
            'user': self.request.user
        })

        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        if self.request.is_ajax():
            response_data = {
                'success': True
            }

            return HttpResponse(json.dumps(response_data), mimetype='application/json')

        return super(DealsCreateView, self).form_valid(form)

    def form_invalid(self, form):
        if self.request.is_ajax():
            response_data = {
                'success': False,
                'errors': form.errors
            }

            return HttpResponseBadRequest(json.dumps(response_data), mimetype='application/json')

        return super(DealsCreateView, self).form_invalid(form)


class DealsUpdateView(UpdateView):
    model = models.Deal
    http_method_names = ['post']
    form_class = forms.DealForm

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: has_active_business_profile(u)))
    def dispatch(self, *args, **kwargs):
        return super(DealsUpdateView, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(DealsUpdateView, self).get_form_kwargs()
        kwargs.update({
            'user':self.request.user,
            'instance': self.object
        })
        return kwargs

    def get_object(self, queryset=None):
        object = super(DealsUpdateView, self).get_object(queryset)
        if self.request.user.has_perm('change_deal', object):
            return object
        else:
            raise PermissionDenied

    def form_valid(self, form):
        form.save()
        if self.request.is_ajax():
            response_data = {
                'success': True
            }

            return HttpResponse(json.dumps(response_data), mimetype='application/json')

        return super(DealsUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        if self.request.is_ajax():

            response_data = {
                'success': False,
                'errors': form.errors
            }

            return HttpResponseBadRequest(json.dumps(response_data), mimetype='application/json')

        return super(DealsUpdateView, self).form_invalid(form)


class DashboardListView(ListView):
    template_name = 'dashboard/dashboard_index.html'

    def get_queryset(self):
        queryset = models.Deal.objects
        queryset = queryset.select_related('ad')

        if self.kwargs:
            return queryset.filter(state=self.kwargs['state'])
        else:
            return queryset.all()

application/apps/deals/templates/deals/deal_activate_deal_modal.html
{% load i18n %}
<form id="deal-activate-{{ deal.pk }}" class="form-horizontal modal hide fade" method="post" ng-controller="DealController" ng-init="id={{ deal.pk }}; action='{{ deal.ACTIVATE }}'" ng-submit="submitDealUpdate()">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>{% trans "Activate deal for ad" %} {{ deal.ad }}</h3>
    </div>
    <div class="modal-body">
        <div ng-show="valid" class="alert alert-success">
            <h3>{% trans "The deal is now activated." %}</h3>
        </div>
        <div ng-hide="valid">
			<p>
				{% trans "By activating this deal you'll be granted access to the other partys contact information." %}
            </p>
			<p>
				<i>
					"The equipment requested is to be considered exclusive for customers who require the equipment which means that the purchase of this equipment, to that particular customer, directly or indirectly, may only be conducted in collaboration with Bidpart AB. Other equipment sold by you to this customer because of the interest in this notice are also included in the fee calculation and reported by you to us."
                </i>
            </p>
            <hr>
            <div class="row-fluid">
                <div class="span2">
                    <label>{% trans 'Quantity' %}</label>
                   {{ deal.amount }}
                </div>
                <div class="span6">
                    <label>{% trans 'Price' %}</label>
                    {{ deal.bid }}
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <p ng-show="!!errors['action']">
            <span class="error" ng-repeat="error in errors['action']">{! error !}</span>
        </p>
        <a href="#deal-{{ deal.pk }}" data-toggle="modal" data-dismiss="modal" class="btn pull-left">{% trans "Close" %}</a>
        <input ng-hide="valid" type="submit" class="btn btn-primary" value="{% trans "Send" %}">
    </div>
</form>

application/apps/deals/templates/deals/deal_cancel_deal_modal.html
{% load i18n %}
<form id="deal-cancel-{{ deal.pk }}" class="form-horizontal modal hide fade" method="post" ng-controller="DealController" ng-init="id={{ deal.pk }}; action='{{ deal.CANCEL }}'" ng-submit="submitDealUpdate()">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>{% trans "Cancel deal for ad" %} {{ deal.ad }}</h3>
    </div>
    <div class="modal-body">
        <div ng-show="valid" class="alert alert-success">
            <h3>{% trans "The deal is now canceled." %}</h3>
        </div>
        <div ng-hide="valid">
            <p>
                {% trans 'To get the statistics, we wish that you give the reason for you to cancel the deal. This information is for internal use only and will not be shown to the other party.' %}
            </p>
            <p>
                {% trans 'In order to offer other equipment we will contact the other party when a deal is cancelled.' %}
            </p>
            <hr>
            <div class="row-fluid">
                <div class="span10">
                   <label>{% trans 'Reason for canceling' %}</label>
                   <textarea name="cancel_reason" ng-model="cancel_reason"></textarea>
                </div>
            </div>
            <ul class="errorlist" ng-show="!!errors['reason']">
                <li ng-repeat="error in errors['reason']">{! error !}</li>
            </ul>
        </div>
    </div>
    <div class="modal-footer">
        <p ng-show="!!errors['action']">
            <span class="error" ng-repeat="error in errors['action']">{! error !}</span>
        </p>
        <a href="#deal-{{ deal.pk }}" data-toggle="modal" data-dismiss="modal" class="btn pull-left">{% trans "Close" %}</a>
        <input ng-hide="valid" type="submit" class="btn btn-primary" value="{% trans "Cancel deal" %}">
    </div>
</form>

application/apps/deals/templates/deals/deal_complete_deal_modal.html
{% load i18n l10n %}
<form id="deal-complete-{{ deal.pk|unlocalize }}" class="form-horizontal modal hide fade" method="post" ng-controller="DealController" ng-init="id={{ deal.pk|unlocalize }}; action='{{ deal.COMPLETE }}'" ng-submit="submitDealUpdate()">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>{% trans "Complete deal for ad" %} {{ deal.ad }}</h3>
    </div>
    <div class="modal-body">
        <div ng-show="valid" class="alert alert-success">
            <h3>{% trans "The deal is now completed." %}</h3>
        </div>
        <div ng-hide="valid">
            <p>
                {% trans 'Please complete the deal by entering the total price for the quantity that have been sold.' %}
            </p>
            <hr>
            <div class="row-fluid">
                <div class="span2">
                    <label for="amount">{% trans 'End quantity' %}</label>
                    <input type="number" name="amount" id="amount" ng-model="amount" min="1" max="{{ deal.ad.amount }}" ng-init="amount={{ deal.amount|unlocalize }}" ng-change="price=amount*{{ deal.float_unit_bid }}">
                    <ul class="errorlist" ng-show="!!errors['amount']">
                        <li ng-repeat="error in errors['amount']">{! error !}</li>
                    </ul>
                </div>
                <div class="span6">
                    <label for="price">{% trans 'End price' %}</label>
                    <div class="input-append amount">
                        <input type="text" id="price" name="price" ng-model="price" ng-init="price=amount*{{ deal.float_unit_bid }}">
                        <div class="add-on">
							{{ deal.currency.code }}
                        </div>
                    </div>

                    <ul class="errorlist" ng-show="!!errors['price']">
                        <li ng-repeat="error in errors['price']">{! error !}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <p ng-show="!!errors['action']">
            <span class="error" ng-repeat="error in errors['action']">{! error !}</span>
        </p>
        <a href="#deal-{{ deal.pk }}" data-toggle="modal" data-dismiss="modal" class="btn pull-left">{% trans "Close" %}</a>
        <input ng-hide="valid" type="submit" class="btn btn-primary" value="{% trans "Complete deal" %}">
    </div>
</form>

application/apps/deals/templates/deals/deal_create_deal_modal.html
{% load i18n l10n %}
<form id="create-deal" class="form-horizontal modal hide fade" method="post" ng-controller="DealController" ng-submit="submitDealCreate()">
    {% csrf_token %}
    <input type="hidden" name="ad" ng-model="ad" id="id_ad" ng-init="ad={{ ad.pk|unlocalize }}" />
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>{% trans "Sign of interest" %}</h3>
    </div>
    <div class="modal-body">
        <div ng-show="valid" class="alert alert-success">
            <h3>{% trans "Your sign of interest is now sent." %}</h3>
        </div>
        <div ng-hide="valid">
            <p>
                {% trans 'With your consent, your contact information will be sent to the owner of the equipment. When the owner is aware of your contact information he can contact you regarding your inquiry.' %}
            </p>
            <hr>
            <ul class="errorlist" ng-show="!!errors['__all__']">
                <li ng-repeat="error in errors['__all__']">{! error !}</li>
            </ul>
            <div class="row-fluid">
                <div class="span2">
                    <label for="amount">{% trans 'Quantity' %}</label>
                    <input type="number" name="amount" id="amount" ng-model="amount" min="1" max="{{ ad.amount }}" ng-change="bid=amount*{{ ad.float_price }}" ng-init="amount={{ ad.amount }}">
                    <ul class="errorlist" ng-show="!!errors['amount']">
                        <li ng-repeat="error in errors['amount']">{! error !}</li>
                    </ul>
                </div>
                <div class="span6">
                    <label for="bid">{% trans 'Price' %}</label>
                    <div class="input-append amount">
                        <input type="text" id="bid" name="bid" ng-disabled="!do_bid" ng-model="bid" ng-init="bid=amount*{{ ad.float_price }}">
                        <div class="add-on">
                            {{ ad.currency.code }}
                        </div>
                    </div>
                    <ul class="errorlist" ng-show="!!errors['bid']">
                        <li ng-repeat="error in errors['bid']">{! error !}</li>
                    </ul>
                    {% if ad.is_request %}
                        <small>{% trans 'Bidparts commission is 10&#37; (minimum € 60) and based on the final price of each individual deal.' %}</small>
                    {% endif %}
                </div>
                <div class="span4">
                    <label class="checkbox do-bid">
                        <input type="checkbox" name="do_bid" class="checkbox" ng-model="do_bid" {% if ad.price == 0 %} ng-init="do_bid=true"{% endif %}>
                        {% trans 'Place your own bid' %}
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0);" ng-hide="valid" data-dismiss="modal" class="btn pull-left">{% trans "Close" %}</a>
        <input ng-hide="valid" type="submit" class="btn btn-primary" value="{% trans "Send" %}">
        <a href="javascript:void(0);" ng-show="valid" data-dismiss="modal" class="btn btn-success">{% trans "Close" %}</a>
    </div>
</form>

application/apps/deals/templates/deals/deal_detail.html
{% extends "base.html" %}

{% block content %}

{{ deal.creator }} ({{ deal.owner }}) har en deal ({{ deal.get_state_display }}) på {{ deal.ad }} som säljs av {{ deal.ad.owner }} ({{ deal.ad.creator }})

{% endblock %}

application/apps/deals/templates/deals/deal_list.html
{% load i18n ads_extras locale_extras %}
{% for deal in ad.deals.all %}
	<div id="deal-{{ deal.pk }}" class="modal hide fade deal-actions">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>{% get_localized deal.ad 'title' %} - {{ deal.owner.business_name }}</h3>
		</div>
        <div class="modal-body">
			{% if deal.state == 'interested' %}
                <p><b>{% trans 'Bid' %}:</b> {{ deal.bid }} {{ deal.currency.code }}</p>
                <p>{% trans 'Begin negotiations to see contact information' %}</p>
			{% else %}
                <p><b>{% trans 'Business name' %}</b>: {{ deal.owner }}</p>
                <p><b>{% trans 'Address' %}</b>: {{ deal.owner.address }} {{ deal.owner.address_zipcode }} {{ deal.owner.address_city }} {{ deal.owner.country }}</p>
                <p><b>{% trans 'Email' %}</b>: {{ deal.creator.user.email }}</p>
                <p><b>{% trans 'Phone' %}</b>: {{ deal.creator.phone }}</p>
				{% if deal.state == 'canceled' %}
                    <p><b>{% trans 'Cancel reason' %}</b>: {{ deal.cancel_reason }}</p>
				{% endif %}
			{% endif %}
        </div>
    	<div class="modal-footer">
			<a data-dismiss="modal" href="#deal-{% if deal.state == 'active' %}extend{% else %}activate{% endif %}-{{ deal.pk }}" class="btn btn-info action negotiation-button{% if deal.state == 'canceled' or deal.state == 'completed' %} disabled{% endif %}" data-toggle="modal">
				{% if deal.state == 'active' %}
					{% trans 'Extend negotiation time' %}
				{% else %}
					{% trans 'Begin negotiations' %}
				{% endif %}
			</a>
			<a data-dismiss="modal" href="#deal-cancel-{{ deal.pk }}" class="btn btn-danger action cancel-button{% if deal.state != 'active' %} disabled{% endif %}{% if deal.state == 'canceled' %} unavailable{% endif %}" data-toggle="modal">
				{% trans 'Cancel deal' %}
			</a>
			<a data-dismiss="modal" href="#deal-complete-{{ deal.pk }}" class="btn btn-success action complete-button{% if deal.state != 'active' %} disabled{% endif %}{% if deal.state == 'completed' %} unavailable{% endif %}" data-toggle="modal">
				{% trans 'Deal complete' %}
			</a>
    	</div>
	</div>
{% endfor %}
<table class="table table-striped">
    <thead>
    	<tr>
            <th>{% trans 'State' %}</th>
            <th>{% trans 'Customer' %}</th>
            <th>{% trans 'Date' %}</th>
            <th>{% trans 'Bid' %}</th>
            <th>&nbsp;</th>
    	</tr>
    </thead>
    <tbody>
    	{% for deal in ad.deals.all %}
			<tr>
				<td>
                    <a href="#deal-{{ deal.pk }}" data-toggle="modal">
						{% if deal.state == 'interested' %}
							<span class="label label-success">
						{% elif deal.state == 'active' %}
							<span class="label label-info">
						{% else %}
							<span class="label">
						{% endif %}
							{{ deal.get_state_display }}
						</span>
                    </a>
				</td>
            	<td>
					<a href="#deal-{{ deal.pk }}" data-toggle="modal">
						{% if deal.state != 'interested' %}
							{{ deal.owner }}
						{% else %}
							{% trans 'Begin negotiations to see contact information' %}
						{% endif %}
                    </a>
                </td>
				<td>
					{{ deal.created|timesince }} {% trans 'ago' %}
				</td>
            	<td>
					<b>{% price deal.bid deal.ad.currency 'price' False %}</b>
					{% if deal.amount > 1 %}
						{{ deal.amount }} {% trans 'pcs' %}
					{% endif %}
            	</td>
            	<td>
                    <a href="#deal-{{ deal.pk }}" class="btn btn-primary btn-small" data-toggle="modal">{% trans 'Show' %}</a>
            	</td>
			</tr>
    	{% endfor %}
    </tbody>
</table>

{% if update_deal_forms %}
	{% for template, form, deal in update_deal_forms %}
		{% include template with form=form deal=deal %}
	{% endfor %}
{% endif %}