application/apps/blog/urls.py
from django.conf.urls import patterns, url
import views


urlpatterns = patterns('',
    url(r'^$', views.BlogListView.as_view(), name='blog_list'),
    url(r'^(?P<slug>[-\w]+)/$', views.BlogDetailView.as_view(), name='blog_view'),
)

application/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

#noinspection PyPackageRequirements
urlpatterns = patterns('',
    # Examples:
    # url(r'^application/', include('application.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),

    url(r'^accounts/', include('application.apps.accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^currencies/', include('currencies.urls')),

    url(r'^notifications/', include('application.libs.notifications.urls', namespace='notifications')),
    url(r'^blog/', include('application.apps.blog.urls', namespace='blog')),
    url(r'^invoice/', include('application.apps.invoice.urls', namespace='invoice')),
    url(r'^page/', include('application.apps.cms.urls', namespace='cms')),
    url(r'^contact/', include('application.apps.contact.urls', namespace='contact')),
    url(r'^faq/', include('application.apps.faq.urls', namespace='faq')),
    url(r'^deals/', include('application.apps.deals.urls', namespace='deals')),

    url(r'^edr/', include('application.apps.edr.urls', namespace='edr')),
    url(r'^interest/', include('application.apps.interest.urls', namespace='interest')),

    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'', include('debug_toolbar_user_panel.urls')),
   )
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^500/$', 'django.views.generic.simple.direct_to_template', {'template': '500.html'}),
        (r'^404/$', 'django.views.generic.simple.direct_to_template', {'template': '404.html'}),

        (r'^template/password_change_done/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_change_done.html'}),
        (r'^template/password_reset_complete/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_complete.html'}),
        (r'^template/password_reset_confirm/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_confirm.html'}),
        (r'^template/password_reset_done/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_done.html'}),
        (r'^template/password_reset_email/$', 'django.views.generic.simple.direct_to_template', {'template': 'registration/password_reset_email.html'}),
    )

urlpatterns += patterns('',
        url(r'^', include('application.apps.ads.urls', namespace='ads')),
   )

application/apps/blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from functions import string_with_title

from application.apps.files.models import Image

import datetime


class BlogEntryManager(models.Manager):
    """ Object manager for BlogEntry class """

    def get_active_entries(self):
        return self.select_related('images').filter(publish__lt=timezone.now(), unpublish__gt=timezone.now(), active=True).order_by('-publish')

    def get_active_entry(self, entry_id):
        return self.get_active_entries().filter(pk=entry_id)[0]

    def get_active_entry_by_slug(self, entry_slug):
        return self.get_active_entries().filter(title_slug=entry_slug)[0]

    def get_latest_entry(self):
        return self.get_active_entries()[0]

    def get_archive(self):
        return self.get_active_entries()  # Todo


class BlogEntry(models.Model):
    """ Main news item class """

    title = models.CharField(max_length=128, verbose_name=_('Title'))
    title_slug = models.CharField(max_length=128, null=True, blank=True, verbose_name=_('Title slug'))
    teaser = models.TextField(null=True, blank=True, verbose_name=_('Text teaser'))
    body = models.TextField(null=True, blank=True, verbose_name=_('Text body'))

    created = models.DateTimeField(blank=True, verbose_name=_('Created'), default=timezone.now())
    updated = models.DateTimeField(blank=True, verbose_name=_('Updated'), default=timezone.now())
    publish = models.DateTimeField(blank=True, verbose_name=_('Publish'), default=timezone.now())
    unpublish = models.DateTimeField(blank=True, verbose_name=_('Unpublish'), default=(timezone.now() + datetime.timedelta(weeks=52 * 100)))

    active = models.BooleanField(verbose_name=_('Active'), default=True)

    images = models.ManyToManyField(Image, through="BlogEntryImage", null=True, blank=True)

    objects = BlogEntryManager()

    def save(self, *args, **kwargs):
        self.title_slug = slugify(self.title)
        if not self.created:
            self.created = timezone.now()
        if not self.updated:
            self.updated = timezone.now()
        if not self.publish:
            self.publish = timezone.now()
        if not self.unpublish:
            self.unpublish = timezone.now() + datetime.timedelta(weeks=52 * 100)

        super(BlogEntry, self).save(*args, **kwargs)

    def number_of_images(self):
        return self.images.count()

    def __unicode__(self):
        return self.title

    class Meta:
        app_label = string_with_title('blog', _('Blog'))
        verbose_name = _("Blog entry")
        verbose_name_plural = _("Blog entries")


class BlogEntryImage(models.Model):
    blog_entry = models.ForeignKey(BlogEntry)
    image = models.ForeignKey(Image, verbose_name=_('Image'))

    def __unicode__(self):
        return str(self.image)

    class Meta:
        app_label = string_with_title('blog', _('Blog'))
        verbose_name = _('Blog entry image')
        verbose_name_plural = _('Blog entry images')

application/apps/blog/views.py
from django.views.generic import DetailView, ListView
from models import BlogEntry


class BlogListView(ListView):
    model = BlogEntry
    template_name = 'blog/blog_list.html'
    paginate_by = 20

    def get_queryset(self):
        return BlogEntry.objects.get_active_entries()


class BlogDetailView(DetailView):
    model = BlogEntry
    template_name = 'blog/blog_detail.html'

    def get_object(self, queryset=None):
        object =  BlogEntry.objects.get_active_entry_by_slug(entry_slug=self.kwargs.get('slug'))
        return object

application/apps/blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block header_search_form %}
    <h1>{% trans 'Blog' %}</h1>
{% endblock %}
{% block content %}

    {% include 'blog/blog_entry.html' with entry=blogentry %}

{% endblock %}

application/apps/blog/templates/blog/blog_entry.html
{% load i18n static %}
<article class="entry blog-entry" id="blog-{{ entry.pk }}">
    <div class="page-header">
        {% if list_view %}
            <h2><a href="{% url blog:blog_view entry.title_slug %}">{{ entry.title }}</a></h2>
        {% else %}
            <h1>{{ entry.title }}</h1>
        {% endif %}
    </div>
    <p><img src="{{ MEDIA_URL }}{{ entry.images.all.0.image_filename }}" /></p>
{#    {% if entry.images.exists %}#}
{#        {% if list_view %}#}
{#            <img src="{{ MEDIA_URL }}{{ entry.images.all.0.image_filename }}" />#}
{#        {% else %}#}
{#            {% for image in entry.images.all %}#}
{#                <img src="{{ MEDIA_URL }}{{ image.image_filename }}" />#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#    {% endif %}#}
    <div class="teaser">
        <strong>{{ entry.teaser|safe }}</strong>
    </div>
    <div class="body">
        {{ entry.body|safe }}
    </div>
    <div class="blog-footer">
        <p>{% trans 'Published' %}: {{ entry.publish|date:"j b Y" }}</p>
    </div>
</article>

application/apps/blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block header_search_form %}
    <h1>{% trans 'Blog' %}</h1>
{% endblock %}
{% block content %}
    <ul class="blog-list">
        {% for entry in blogentry_list %}
            <li>{% include 'blog/blog_entry.html' with entry=entry list_view=1 %}</li>
        {% empty %}
            <li>{% trans 'No blog entries found.' %}</li>
        {% endfor %}
     </ul>
    {#% pagination %#}
{% endblock %}